### ISSUE TITLE
cp is missing recursive mode

### ISSUE THREAD

**Issue by more-turtles** [EricLagerg/gonix#2]
To copy a directory:

    cp -r source destination

**Comment by EricLagerg** [comment]
It's worth noting that if you choose to follow symlinks, a library for finding infinite loops in the file hierarchy needs to be found, otherwise an infinite loop will run something like over 60,000 times before Go kills it.

**Comment by 0xCMP** [comment]
Can’t we just track inodes? I guess that wouldn’t be cross-platform for everything but it’d work for *nix systems I think.


-- cmp

**Comment by EricLagerg** [comment]
Yes (and rdev too, since I think inodes are rdev specific).

The algorithm matters too. IIRC, GNU doesn't use a simple map lookup.

**Comment by 0xCMP** [comment]
Really? It’s so crazy how complex these tools really end up being are when you get down to core of them or try to remake them.


-- cmp

**Comment by EricLagerg** [comment]
Yeah! It's been a lot of (super nerdy) fun getting to learn the insides of these utilities. 

I'll post a link to the algo when I get to work.

**Comment by EricLagerg** [comment]
fts algorithm used: https://github.com/coreutils/gnulib/blob/master/lib/fts-cycle.c & https://github.com/coreutils/gnulib/blob/master/lib/fts.c & https://github.com/coreutils/gnulib/blob/master/lib/fts_.h
